/**
 * ExamQuestionAdder — 4-tab dialog for adding questions to exams
 *
 * Tab 1: Manual — directly type a question
 * Tab 2: CSV Upload — bulk upload via CSV file
 * Tab 3: Import from Question Bank — browse/filter/select from bank
 * Tab 4: Auto Generate — auto-generate questions from question bank with filters
 */
import { useState, useEffect } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { useAcademicCalendar } from '@/hooks/useAcademicCalendar';
import { apiRequest, queryClient } from '@/lib/queryClient';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import {
    PenLine, Upload, Database, Search, Filter,
    CheckCircle2, XCircle, AlertTriangle, Plus, Trash2,
    Wand2, RefreshCw, Sparkles, Loader2
} from 'lucide-react';
import { BulkCSVUploadPanel } from '@/components/shared/BulkCSVQuestionsDialog';
import type { ParsedQuestion } from '@/components/shared/BulkCSVQuestionsDialog';

interface ExamQuestionAdderProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    examId: number;
    examClassId?: number;
    examSubjectId?: number;
    onQuestionsAdded: () => void;
}

export default function ExamQuestionAdder({
    open, onOpenChange, examId, examClassId, examSubjectId, onQuestionsAdded
}: ExamQuestionAdderProps) {
    const { toast } = useToast();

    // ═══ TAB STATE ═══
    const [activeTab, setActiveTab] = useState('manual');

    // ═══ CSV TAB STATE ═══
    const [csvServerErrors, setCsvServerErrors] = useState<string[]>([]);

    // ═══ MANUAL TAB STATE ═══
    const [questionText, setQuestionText] = useState('');
    const [questionType, setQuestionType] = useState('multiple_choice');
    const [points, setPoints] = useState('1');
    const [options, setOptions] = useState([
        { text: '', isCorrect: false },
        { text: '', isCorrect: false },
        { text: '', isCorrect: false },
        { text: '', isCorrect: false },
    ]);
    const [expectedAnswer, setExpectedAnswer] = useState('');
    const [instructions, setInstructions] = useState('');
    const [sampleAnswer, setSampleAnswer] = useState('');

    // ═══ BANK IMPORT TAB STATE ═══
    const [bankFilterClassId, setBankFilterClassId] = useState(examClassId ? String(examClassId) : '');
    const [bankFilterSubjectId, setBankFilterSubjectId] = useState(examSubjectId ? String(examSubjectId) : '');
    const [bankFilterTermId, setBankFilterTermId] = useState('');
    const [bankFilterBankId, setBankFilterBankId] = useState('');
    const [bankFilterTopicId, setBankFilterTopicId] = useState('');
    const [bankFilterDifficulty, setBankFilterDifficulty] = useState('');
    const [bankFilterType, setBankFilterType] = useState('');
    const [selectedBankItems, setSelectedBankItems] = useState<Set<number>>(new Set());

    // ═══ AUTO GENERATE TAB STATE ═══
    const [autoClassId, setAutoClassId] = useState(examClassId ? String(examClassId) : '');
    const [autoSubjectId, setAutoSubjectId] = useState(examSubjectId ? String(examSubjectId) : '');
    const [autoTermId, setAutoTermId] = useState('');
    const [autoTopicId, setAutoTopicId] = useState('');
    const [autoCount, setAutoCount] = useState('10');
    const [autoQuestionType, setAutoQuestionType] = useState('all');
    const [autoDifficulty, setAutoDifficulty] = useState('mixed');
    const [autoGeneratedQuestions, setAutoGeneratedQuestions] = useState<any[]>([]);
    const [autoTotalAvailable, setAutoTotalAvailable] = useState<number | null>(null);
    const [autoShortfall, setAutoShortfall] = useState<string | null>(null);

    // ═══ REFERENCE DATA ═══
    const { data: classes = [] } = useQuery({
        queryKey: ['/api/classes'],
        queryFn: async () => { const r = await apiRequest('GET', '/api/classes'); return r.json(); },
    });
    const { data: subjects = [] } = useQuery({
        queryKey: ['/api/subjects'],
        queryFn: async () => { const r = await apiRequest('GET', '/api/subjects'); return r.json(); },
    });
    const { currentTerm, allTerms: terms } = useAcademicCalendar();

    // Auto-select current term in the bank filter and auto-generate filter
    useEffect(() => {
        if (currentTerm) {
            if (!bankFilterTermId) setBankFilterTermId(String(currentTerm.id));
            if (!autoTermId) setAutoTermId(String(currentTerm.id));
        }
    }, [currentTerm]);

    // ═══ BANK IMPORT — available banks (requires class + subject + term) ═══
    const { data: importBanks = [] } = useQuery({
        queryKey: ['/api/question-banks', 'import', bankFilterClassId, bankFilterSubjectId, bankFilterTermId],
        queryFn: async () => {
            const params = new URLSearchParams();
            if (bankFilterClassId)   params.set('classId',   bankFilterClassId);
            if (bankFilterSubjectId) params.set('subjectId', bankFilterSubjectId);
            if (bankFilterTermId)    params.set('termId',    bankFilterTermId);
            const r = await apiRequest('GET', `/api/question-banks?${params.toString()}`);
            return r.ok ? r.json() : [];
        },
        enabled: !!(bankFilterClassId && bankFilterSubjectId && bankFilterTermId),
        staleTime: 30_000,
    });

    const { data: bankTopics = [] } = useQuery({
        queryKey: ['/api/syllabus-topics', 'bank-import', bankFilterClassId, bankFilterSubjectId, bankFilterTermId],
        queryFn: async () => {
            const params = new URLSearchParams();
            if (bankFilterClassId)   params.set('classId',   bankFilterClassId);
            if (bankFilterSubjectId) params.set('subjectId', bankFilterSubjectId);
            if (bankFilterTermId)    params.set('termId',    bankFilterTermId);
            const r = await apiRequest('GET', `/api/syllabus-topics?${params.toString()}`);
            return r.ok ? r.json() : [];
        },
        enabled: !!(bankFilterClassId && bankFilterSubjectId && bankFilterTermId),
    });

    // ═══ AUTO GENERATE TOPICS ═══
    const { data: autoTopics = [] } = useQuery({
        queryKey: ['/api/syllabus-topics', 'auto-gen', autoClassId, autoSubjectId, autoTermId],
        queryFn: async () => {
            const params = new URLSearchParams();
            if (autoClassId) params.set('classId', autoClassId);
            if (autoSubjectId) params.set('subjectId', autoSubjectId);
            if (autoTermId) params.set('termId', autoTermId);
            const r = await apiRequest('GET', `/api/syllabus-topics?${params.toString()}`);
            return r.ok ? r.json() : [];
        },
        enabled: !!(autoClassId && autoSubjectId && autoTermId),
    });

    // ═══ BANK ITEMS QUERY — requires bankId + classId + termId ═══
    const { data: bankItems = [], isLoading: loadingBankItems } = useQuery({
        queryKey: ['/api/question-bank/items', 'import', bankFilterClassId, bankFilterTermId, bankFilterBankId, bankFilterTopicId, bankFilterDifficulty, bankFilterType],
        queryFn: async () => {
            const params = new URLSearchParams();
            params.set('classId',  bankFilterClassId);
            params.set('termId',   bankFilterTermId);
            params.set('bankId',   bankFilterBankId);
            params.set('fetchAll', 'true');
            if (bankFilterTopicId)    params.set('topicId',      bankFilterTopicId);
            if (bankFilterDifficulty) params.set('difficulty',   bankFilterDifficulty);
            if (bankFilterType)       params.set('questionType', bankFilterType);
            const r = await apiRequest('GET', `/api/question-bank/items?${params.toString()}`);
            if (!r.ok) return [];
            const data = await r.json();
            return Array.isArray(data) ? data : (data.items ?? []);
        },
        enabled: open && activeTab === 'bank' && !!(bankFilterClassId && bankFilterTermId && bankFilterBankId),
    });

    // ═══ MUTATIONS ═══
    // Manual question creation
    const createManualMutation = useMutation({
        mutationFn: async (data: any) => {
            const r = await apiRequest('POST', '/api/exam-questions', data);
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || err.message || 'Failed'); }
            return r.json();
        },
        onSuccess: () => {
            toast({ title: 'Success', description: 'Question added to exam' });
            queryClient.invalidateQueries({ queryKey: ['/api/exam-questions', examId] });
            queryClient.invalidateQueries({ queryKey: ['/api/exams/question-counts'] });
            resetManualForm();
            onQuestionsAdded();
        },
        onError: (e: any) => toast({ title: 'Error', description: e.message, variant: 'destructive' }),
    });

    // CSV bulk upload to exam
    const csvUploadMutation = useMutation({
        mutationFn: async (questions: ParsedQuestion[]) => {
            const r = await apiRequest('POST', '/api/exam-questions/bulk', { examId, questions });
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || 'Upload failed'); }
            return r.json();
        },
        onSuccess: (result) => {
            const serverErrs: string[] = result.errors ?? [];
            toast({ title: 'Success', description: `${result.created} question${result.created !== 1 ? 's' : ''} added.${serverErrs.length ? ` ${serverErrs.length} row(s) skipped — see details below.` : ''}` });
            queryClient.invalidateQueries({ queryKey: ['/api/exam-questions', examId] });
            queryClient.invalidateQueries({ queryKey: ['/api/exams/question-counts'] });
            if (serverErrs.length) {
                setCsvServerErrors(serverErrs); // surface row errors in-panel
            } else {
                setCsvServerErrors([]);
                onQuestionsAdded();
            }
        },
        onError: (e: any) => toast({ title: 'Upload Error', description: e.message, variant: 'destructive' }),
    });

    // Import from question bank
    const importBankMutation = useMutation({
        mutationFn: async (itemIds: number[]) => {
            const r = await apiRequest('POST', '/api/question-bank/import-to-exam', {
                examId, questionItemIds: itemIds,
            });
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || 'Import failed'); }
            return r.json();
        },
        onSuccess: (result) => {
            toast({ title: 'Success', description: `${result.imported} question${result.imported !== 1 ? 's' : ''} imported from bank.` });
            queryClient.invalidateQueries({ queryKey: ['/api/exam-questions', examId] });
            queryClient.invalidateQueries({ queryKey: ['/api/exams/question-counts'] });
            setSelectedBankItems(new Set());
            onQuestionsAdded();
        },
        onError: (e: any) => toast({ title: 'Import Error', description: e.message, variant: 'destructive' }),
    });

    // Auto-generate questions from bank
    const autoGenerateMutation = useMutation({
        mutationFn: async () => {
            const r = await apiRequest('POST', '/api/question-bank/auto-generate', {
                classId: autoClassId, subjectId: autoSubjectId, termId: autoTermId,
                topicId: (autoTopicId && autoTopicId !== 'all') ? autoTopicId : undefined,
                count: autoCount, questionType: autoQuestionType, difficulty: autoDifficulty,
            });
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || 'Generation failed'); }
            return r.json();
        },
        onSuccess: (result) => {
            setAutoGeneratedQuestions(result.questions || []);
            setAutoTotalAvailable(result.totalAvailable ?? null);
            setAutoShortfall(result.shortfall ?? null);
            if (result.questions?.length > 0) {
                toast({ title: 'Success', description: `${result.questions.length} question${result.questions.length !== 1 ? 's' : ''} ready for review.` });
            } else {
                toast({ title: 'No Questions Found', description: 'No questions match your filters. Try adjusting your criteria.', variant: 'destructive' });
            }
        },
        onError: (e: any) => toast({ title: 'Generation Error', description: e.message, variant: 'destructive' }),
    });

    // Import auto-generated questions to exam
    const importAutoGeneratedMutation = useMutation({
        mutationFn: async (itemIds: number[]) => {
            const r = await apiRequest('POST', '/api/question-bank/import-to-exam', {
                examId, questionItemIds: itemIds,
            });
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || 'Import failed'); }
            return r.json();
        },
        onSuccess: (result) => {
            toast({ title: 'Success', description: `${result.imported} question${result.imported !== 1 ? 's' : ''} added to exam.` });
            queryClient.invalidateQueries({ queryKey: ['/api/exam-questions', examId] });
            queryClient.invalidateQueries({ queryKey: ['/api/exams/question-counts'] });
            setAutoGeneratedQuestions([]);
            setAutoShortfall(null);
            setAutoTotalAvailable(null);
            onQuestionsAdded();
        },
        onError: (e: any) => toast({ title: 'Import Error', description: e.message, variant: 'destructive' }),
    });

    // Replace a single auto-generated question
    const replaceAutoQuestionMutation = useMutation({
        mutationFn: async (questionIdToReplace: number) => {
            const excludeIds = autoGeneratedQuestions.map((q: any) => q.id);
            const r = await apiRequest('POST', '/api/question-bank/auto-generate', {
                classId: autoClassId, subjectId: autoSubjectId, termId: autoTermId,
                topicId: (autoTopicId && autoTopicId !== 'all') ? autoTopicId : undefined,
                count: 1, questionType: autoQuestionType, difficulty: autoDifficulty,
                excludeIds,
            });
            if (!r.ok) { const err = await r.json(); throw new Error(err.error || 'Replace failed'); }
            const result = await r.json();
            return { replacement: result.questions?.[0], replacedId: questionIdToReplace };
        },
        onSuccess: ({ replacement, replacedId }) => {
            if (replacement) {
                setAutoGeneratedQuestions(prev =>
                    prev.map(q => q.id === replacedId ? replacement : q)
                );
                toast({ title: 'Success', description: 'Question swapped with another from the bank.' });
            } else {
                toast({ title: 'No Replacement Available', description: 'No more questions match your filters', variant: 'destructive' });
            }
        },
        onError: (e: any) => toast({ title: 'Replace Error', description: e.message, variant: 'destructive' }),
    });

    // ═══ HELPERS ═══
    const resetManualForm = () => {
        setQuestionText(''); setQuestionType('multiple_choice'); setPoints('1');
        setOptions([{ text: '', isCorrect: false }, { text: '', isCorrect: false }, { text: '', isCorrect: false }, { text: '', isCorrect: false }]);
        setExpectedAnswer(''); setInstructions(''); setSampleAnswer('');
    };

    const handleManualSubmit = () => {
        if (!questionText.trim() || questionText.trim().length < 5) {
            return toast({ title: 'Error', description: 'Question text must be at least 5 characters', variant: 'destructive' });
        }
        const data: any = {
            examId, questionText: questionText.trim(), questionType,
            points: parseInt(points) || 1, orderNumber: 0,
        };
        if (instructions) data.instructions = instructions;
        if (sampleAnswer) data.sampleAnswer = sampleAnswer;

        if (questionType === 'multiple_choice') {
            const valid = options.filter(o => o.text.trim());
            if (valid.length < 2) return toast({ title: 'Error', description: 'At least 2 options required', variant: 'destructive' });
            if (!valid.some(o => o.isCorrect)) return toast({ title: 'Error', description: 'Mark at least one correct option', variant: 'destructive' });
            data.options = valid.map((o, i) => ({ optionText: o.text.trim(), isCorrect: o.isCorrect }));
        } else if (expectedAnswer) {
            data.expectedAnswers = JSON.stringify([expectedAnswer]);
        }
        createManualMutation.mutate(data);
    };

    // Bank item helpers
    const toggleBankItem = (id: number) => {
        const next = new Set(selectedBankItems);
        if (next.has(id)) next.delete(id); else next.add(id);
        setSelectedBankItems(next);
    };
    const toggleAllBankItems = () => {
        if (selectedBankItems.size === bankItems.length) {
            setSelectedBankItems(new Set());
        } else {
            setSelectedBankItems(new Set(bankItems.map((q: any) => q.id)));
        }
    };
    const handleBankFilterClassChange = (v: string) => { setBankFilterClassId(v); setBankFilterTermId(''); setBankFilterBankId(''); setBankFilterTopicId(''); };
    const handleBankFilterTermChange = (v: string) => { setBankFilterTermId(v); setBankFilterBankId(''); setBankFilterTopicId(''); };

    // Auto Generate helpers
    const handleAutoClassChange = (v: string) => { setAutoClassId(v); setAutoTermId(''); setAutoTopicId(''); setAutoGeneratedQuestions([]); };
    const handleAutoTermChange = (v: string) => { setAutoTermId(v); setAutoTopicId(''); setAutoGeneratedQuestions([]); };
    const removeAutoQuestion = (id: number) => { setAutoGeneratedQuestions(prev => prev.filter(q => q.id !== id)); };
    const canAutoGenerate = autoClassId && autoSubjectId && autoTermId && parseInt(autoCount) > 0;
    const autoMcqCount = autoGeneratedQuestions.filter((q: any) => q.questionType === 'multiple_choice').length;
    const autoTheoryCount = autoGeneratedQuestions.length - autoMcqCount;

    const getDifficultyColor = (d: string) => {
        switch (d) { case 'easy': return 'bg-green-100 text-green-800'; case 'hard': return 'bg-red-100 text-red-800'; default: return 'bg-yellow-100 text-yellow-800'; }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <Plus className="w-5 h-5" /> Add Questions to Exam
                    </DialogTitle>
                </DialogHeader>

                <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                    <TabsList className="grid w-full grid-cols-4">
                        <TabsTrigger value="manual" className="flex items-center gap-1.5 text-xs sm:text-sm">
                            <PenLine className="w-4 h-4" /> <span className="hidden sm:inline">Manual</span>
                        </TabsTrigger>
                        <TabsTrigger value="csv" className="flex items-center gap-1.5 text-xs sm:text-sm">
                            <Upload className="w-4 h-4" /> <span className="hidden sm:inline">CSV</span>
                        </TabsTrigger>
                        <TabsTrigger value="bank" className="flex items-center gap-1.5 text-xs sm:text-sm">
                            <Database className="w-4 h-4" /> <span className="hidden sm:inline">From Bank</span>
                        </TabsTrigger>
                        <TabsTrigger value="auto" className="flex items-center gap-1.5 text-xs sm:text-sm">
                            <Wand2 className="w-4 h-4" /> <span className="hidden sm:inline">Auto Generate</span>
                        </TabsTrigger>
                    </TabsList>

                    {/* ═══ TAB 1: MANUAL ═══ */}
                    <TabsContent value="manual" className="space-y-4 mt-4">
                        <div>
                            <Label>Question Text *</Label>
                            <Textarea value={questionText} onChange={(e) => setQuestionText(e.target.value)} placeholder="Enter your question..." rows={3} />
                        </div>
                        <div className="grid grid-cols-3 gap-3">
                            <div>
                                <Label>Type</Label>
                                <Select value={questionType} onValueChange={setQuestionType}>
                                    <SelectTrigger><SelectValue /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="multiple_choice">Multiple Choice</SelectItem>
                                        <SelectItem value="essay">Essay</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                            <div>
                                <Label>Points</Label>
                                <Input type="number" value={points} onChange={(e) => setPoints(e.target.value)} min="1" />
                            </div>
                            <div>
                                <Label>Instructions</Label>
                                <Input value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder="Optional" />
                            </div>
                        </div>

                        {questionType === 'multiple_choice' && (
                            <div className="border-t pt-3">
                                <Label>Options (check correct answer)</Label>
                                <div className="space-y-2 mt-2">
                                    {options.map((opt, i) => (
                                        <div key={i} className="flex items-center gap-2">
                                            <input type="checkbox" checked={opt.isCorrect} onChange={(e) => {
                                                const n = [...options]; n[i].isCorrect = e.target.checked; setOptions(n);
                                            }} className="w-4 h-4" />
                                            <Input value={opt.text} onChange={(e) => {
                                                const n = [...options]; n[i].text = e.target.value; setOptions(n);
                                            }} placeholder={`Option ${String.fromCharCode(65 + i)}`} className="h-9" />
                                            {options.length > 2 && (
                                                <Button variant="ghost" size="sm" onClick={() => setOptions(options.filter((_, j) => j !== i))}>
                                                    <Trash2 className="w-3 h-3" />
                                                </Button>
                                            )}
                                        </div>
                                    ))}
                                    {options.length < 6 && (
                                        <Button variant="ghost" size="sm" onClick={() => setOptions([...options, { text: '', isCorrect: false }])}>
                                            <Plus className="w-3 h-3 mr-1" /> Add Option
                                        </Button>
                                    )}
                                </div>
                            </div>
                        )}

                        {questionType === 'essay' && (
                            <div>
                                <Label>Sample Answer</Label>
                                <Textarea value={sampleAnswer} onChange={(e) => setSampleAnswer(e.target.value)}
                                    placeholder="Reference answer for grading" rows={3} />
                            </div>
                        )}

                        <div className="flex justify-end gap-2 pt-2">
                            <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                            <Button onClick={handleManualSubmit} disabled={createManualMutation.isPending}>
                                {createManualMutation.isPending ? 'Adding...' : 'Add Question'}
                            </Button>
                        </div>
                    </TabsContent>

                    {/* ═══ TAB 2: CSV UPLOAD ═══ */}
                    <TabsContent value="csv" className="mt-4">
                        <BulkCSVUploadPanel
                            onUpload={(questions) => { setCsvServerErrors([]); csvUploadMutation.mutate(questions); }}
                            isPending={csvUploadMutation.isPending}
                            onCancel={() => onOpenChange(false)}
                            serverErrors={csvServerErrors}
                        />
                    </TabsContent>

                    {/* ═══ TAB 3: IMPORT FROM QUESTION BANK ═══ */}
                    <TabsContent value="bank" className="space-y-4 mt-4">
                        {/* Filters */}
                        <div className="border rounded-lg p-3 bg-muted/30">
                            <div className="flex items-center justify-between mb-2">
                                <span className="text-xs font-medium flex items-center gap-1"><Filter className="w-3 h-3" /> Filter Questions</span>
                                <Button variant="ghost" size="sm" className="h-6 text-xs" onClick={() => {
                                    setBankFilterClassId(''); setBankFilterSubjectId(''); setBankFilterTermId('');
                                    setBankFilterBankId(''); setBankFilterTopicId(''); setBankFilterDifficulty(''); setBankFilterType('');
                                }}>Clear</Button>
                            </div>
                            <p className="text-[10px] text-muted-foreground mb-2">Class, Subject, Term and Bank are all required to search.</p>
                            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                                <Select value={bankFilterClassId} onValueChange={handleBankFilterClassChange}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Class *" /></SelectTrigger>
                                    <SelectContent>{(classes as any[]).map((c: any) => <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent>
                                </Select>
                                <Select value={bankFilterSubjectId} onValueChange={(v) => { setBankFilterSubjectId(v); setBankFilterBankId(''); setBankFilterTopicId(''); }}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Subject *" /></SelectTrigger>
                                    <SelectContent>{(subjects as any[]).map((s: any) => <SelectItem key={s.id} value={String(s.id)}>{s.name}</SelectItem>)}</SelectContent>
                                </Select>
                                <Select value={bankFilterTermId} onValueChange={handleBankFilterTermChange}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Term *" /></SelectTrigger>
                                    <SelectContent>{(terms as any[]).map((t: any) => <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent>
                                </Select>
                                <Select value={bankFilterBankId} onValueChange={(v) => { setBankFilterBankId(v); setBankFilterTopicId(''); }}
                                    disabled={!bankFilterClassId || !bankFilterSubjectId || !bankFilterTermId}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder={
                                        !bankFilterClassId || !bankFilterSubjectId || !bankFilterTermId ? 'Set class/subject/term first' :
                                        (importBanks as any[]).length === 0 ? 'No banks found' : 'Bank *'
                                    } /></SelectTrigger>
                                    <SelectContent>
                                        {(importBanks as any[]).length === 0 ? (
                                            <div className="px-3 py-2 text-xs text-muted-foreground">No banks for this selection</div>
                                        ) : (
                                            (importBanks as any[]).map((b: any) => <SelectItem key={b.id} value={String(b.id)}>{b.name}</SelectItem>)
                                        )}
                                    </SelectContent>
                                </Select>
                            </div>
                            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mt-2">
                                <Select value={bankFilterTopicId || '_all'} onValueChange={(v) => setBankFilterTopicId(v === '_all' ? '' : v)}
                                    disabled={!bankFilterBankId}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder={!bankFilterBankId ? 'Select bank first' : 'Topic (optional)'} /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="_all">All topics</SelectItem>
                                        {(bankTopics as any[]).map((t: any) => <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}
                                    </SelectContent>
                                </Select>
                                <Select value={bankFilterDifficulty || '_all'} onValueChange={(v) => setBankFilterDifficulty(v === '_all' ? '' : v)}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Difficulty" /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="_all">Any difficulty</SelectItem>
                                        <SelectItem value="easy">Easy</SelectItem>
                                        <SelectItem value="medium">Medium</SelectItem>
                                        <SelectItem value="hard">Hard</SelectItem>
                                    </SelectContent>
                                </Select>
                                <Select value={bankFilterType || '_all'} onValueChange={(v) => setBankFilterType(v === '_all' ? '' : v)}>
                                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="All types" /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="_all">All types</SelectItem>
                                        <SelectItem value="multiple_choice">Multiple Choice</SelectItem>
                                        <SelectItem value="essay">Essay</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                        </div>

                        {/* Question list with checkboxes */}
                        <div className="border rounded-lg">
                            <div className="p-2 bg-muted/50 flex items-center justify-between rounded-t-lg">
                                <div className="flex items-center gap-2">
                                    <input type="checkbox"
                                        checked={bankItems.length > 0 && selectedBankItems.size === bankItems.length}
                                        onChange={toggleAllBankItems}
                                        className="w-4 h-4" />
                                    <span className="text-sm font-medium">
                                        {loadingBankItems ? 'Loading...' : `${bankItems.length} question${bankItems.length !== 1 ? 's' : ''} available`}
                                    </span>
                                </div>
                                {selectedBankItems.size > 0 && (
                                    <Badge>{selectedBankItems.size} selected</Badge>
                                )}
                            </div>
                            <div className="max-h-72 overflow-y-auto divide-y">
                                {bankItems.length === 0 && !loadingBankItems && (
                                    <div className="p-6 text-center text-sm text-muted-foreground">
                                        <Database className="w-8 h-8 mx-auto mb-2 opacity-30" />
                                        {!bankFilterBankId
                                            ? 'Select Class, Subject, Term and Bank to load questions.'
                                            : 'No questions found. Try adjusting filters.'}
                                    </div>
                                )}
                                {bankItems.map((q: any) => (
                                    <div key={q.id}
                                        className={`p-3 flex items-start gap-3 cursor-pointer hover:bg-muted/30 transition-colors ${selectedBankItems.has(q.id) ? 'bg-primary/5' : ''}`}
                                        onClick={() => toggleBankItem(q.id)}
                                    >
                                        <input type="checkbox"
                                            checked={selectedBankItems.has(q.id)}
                                            onChange={() => toggleBankItem(q.id)}
                                            className="w-4 h-4 mt-0.5 shrink-0" />
                                        <div className="flex-1 min-w-0">
                                            <div className="flex items-center gap-1.5 mb-1 flex-wrap">
                                                <Badge variant="outline" className="text-[10px]">
                                                    {q.questionType === 'multiple_choice' ? 'MCQ' : q.questionType}
                                                </Badge>
                                                <Badge className={`text-[10px] ${getDifficultyColor(q.difficulty)}`}>{q.difficulty}</Badge>
                                                <Badge variant="secondary" className="text-[10px]">{q.points}pt</Badge>
                                            </div>
                                            <p className="text-sm line-clamp-2">{q.questionText}</p>
                                            {q.options?.length > 0 && (
                                                <div className="mt-1.5 flex flex-wrap gap-1">
                                                    {q.options.slice(0, 4).map((o: any, i: number) => (
                                                        <span key={i} className={`text-[10px] px-1.5 py-0.5 rounded ${o.isCorrect ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}`}>
                                                            {o.isCorrect ? '✓' : ''} {o.optionText}
                                                        </span>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div className="flex justify-end gap-2">
                            <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                            <Button onClick={() => importBankMutation.mutate(Array.from(selectedBankItems))}
                                disabled={selectedBankItems.size === 0 || importBankMutation.isPending}>
                                {importBankMutation.isPending ? 'Importing...' : `Import ${selectedBankItems.size} Question${selectedBankItems.size !== 1 ? 's' : ''}`}
                            </Button>
                        </div>
                    </TabsContent>

                    {/* ═══ TAB 4: AUTO GENERATE FROM QUESTION BANK ═══ */}
                    <TabsContent value="auto" className="space-y-4 mt-4">
                        {/* Filter Form */}
                        <div className="border rounded-lg p-4 bg-gradient-to-br from-violet-50/50 to-purple-50/50 dark:from-violet-950/20 dark:to-purple-950/20">
                            <div className="flex items-center gap-2 mb-3">
                                <Sparkles className="w-4 h-4 text-violet-600 dark:text-violet-400" />
                                <span className="text-sm font-semibold text-violet-800 dark:text-violet-200">Auto Generate Settings</span>
                            </div>
                            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                                <div>
                                    <Label className="text-xs">Class *</Label>
                                    <Select value={autoClassId} onValueChange={handleAutoClassChange}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select class" /></SelectTrigger>
                                        <SelectContent>{classes.map((c: any) => <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label className="text-xs">Subject *</Label>
                                    <Select value={autoSubjectId} onValueChange={(v) => { setAutoSubjectId(v); setAutoGeneratedQuestions([]); }}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select subject" /></SelectTrigger>
                                        <SelectContent>{subjects.map((s: any) => <SelectItem key={s.id} value={String(s.id)}>{s.name}</SelectItem>)}</SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label className="text-xs">Term *</Label>
                                    <Select value={autoTermId} onValueChange={handleAutoTermChange}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue placeholder="Select term" /></SelectTrigger>
                                        <SelectContent>{terms.map((t: any) => <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label className="text-xs">Topic</Label>
                                    <Select value={autoTopicId} onValueChange={(v) => { setAutoTopicId(v); setAutoGeneratedQuestions([]); }} disabled={!autoClassId || !autoSubjectId || !autoTermId}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue placeholder={!autoClassId || !autoSubjectId || !autoTermId ? 'Set class/subject/term' : 'All topics'} /></SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="all">All Topics</SelectItem>
                                            {autoTopics.map((t: any) => <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label className="text-xs">Question Type</Label>
                                    <Select value={autoQuestionType} onValueChange={(v) => { setAutoQuestionType(v); setAutoGeneratedQuestions([]); }}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue /></SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="all">All Types</SelectItem>
                                            <SelectItem value="multiple_choice">MCQ Only</SelectItem>
                                            <SelectItem value="essay">Essay Only</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label className="text-xs">Difficulty</Label>
                                    <Select value={autoDifficulty} onValueChange={(v) => { setAutoDifficulty(v); setAutoGeneratedQuestions([]); }}>
                                        <SelectTrigger className="h-9 text-xs"><SelectValue /></SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="mixed">Mixed</SelectItem>
                                            <SelectItem value="easy">Easy</SelectItem>
                                            <SelectItem value="medium">Medium</SelectItem>
                                            <SelectItem value="hard">Hard</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                            </div>
                            <div className="flex items-end gap-3 mt-3">
                                <div className="w-32">
                                    <Label className="text-xs">No. of Questions *</Label>
                                    <Input
                                        type="number" min="1" max="100"
                                        value={autoCount}
                                        onChange={(e) => setAutoCount(e.target.value)}
                                        className="h-9 text-xs"
                                        placeholder="10"
                                    />
                                </div>
                                <Button
                                    onClick={() => autoGenerateMutation.mutate()}
                                    disabled={!canAutoGenerate || autoGenerateMutation.isPending}
                                    className="h-9 bg-primary hover:bg-primary/90 text-white"
                                    size="sm"
                                >
                                    {autoGenerateMutation.isPending ? (
                                        <><Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> Generating...</>
                                    ) : (
                                        <><Wand2 className="w-4 h-4 mr-1.5" /> Generate Questions</>
                                    )}
                                </Button>
                            </div>
                        </div>

                        {/* Shortfall Warning */}
                        {autoShortfall && (
                            <div className="flex items-center gap-2 p-2.5 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg">
                                <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
                                <p className="text-xs text-amber-700 dark:text-amber-300">{autoShortfall}</p>
                            </div>
                        )}

                        {/* Generated Questions Preview */}
                        {autoGeneratedQuestions.length > 0 && (
                            <div className="border rounded-lg">
                                <div className="p-2.5 bg-muted/50 flex items-center justify-between rounded-t-lg">
                                    <div className="flex items-center gap-2">
                                        <Sparkles className="w-4 h-4 text-violet-600" />
                                        <span className="text-sm font-medium">
                                            {autoGeneratedQuestions.length} question{autoGeneratedQuestions.length !== 1 ? 's' : ''} ready
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        {autoMcqCount > 0 && <Badge variant="secondary" className="text-[10px]">{autoMcqCount} MCQ</Badge>}
                                        {autoTheoryCount > 0 && <Badge variant="secondary" className="text-[10px]">{autoTheoryCount} Theory</Badge>}
                                        {autoTotalAvailable !== null && (
                                            <Badge variant="outline" className="text-[10px]">{autoTotalAvailable} in bank</Badge>
                                        )}
                                    </div>
                                </div>
                                <div className="max-h-72 overflow-y-auto divide-y">
                                    {autoGeneratedQuestions.map((q: any, idx: number) => (
                                        <div key={q.id} className="p-3 flex items-start gap-3 group hover:bg-muted/20 transition-colors">
                                            <span className="text-xs font-mono text-muted-foreground mt-0.5 w-5 shrink-0">{idx + 1}.</span>
                                            <div className="flex-1 min-w-0">
                                                <div className="flex items-center gap-1.5 mb-1 flex-wrap">
                                                    <Badge variant="outline" className="text-[10px]">
                                                        {q.questionType === 'multiple_choice' ? 'MCQ' : q.questionType}
                                                    </Badge>
                                                    <Badge className={`text-[10px] ${getDifficultyColor(q.difficulty)}`}>{q.difficulty}</Badge>
                                                    <Badge variant="secondary" className="text-[10px]">{q.points}pt</Badge>
                                                </div>
                                                <p className="text-sm line-clamp-2">{q.questionText}</p>
                                                {q.options?.length > 0 && (
                                                    <div className="mt-1.5 flex flex-wrap gap-1">
                                                        {q.options.slice(0, 4).map((o: any, i: number) => (
                                                            <span key={i} className={`text-[10px] px-1.5 py-0.5 rounded ${o.isCorrect ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' : 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400'}`}>
                                                                {o.isCorrect ? '✓' : ''} {o.optionText}
                                                            </span>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>
                                            <div className="flex items-center gap-1 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <Button
                                                    variant="ghost" size="sm"
                                                    className="h-7 w-7 p-0 text-muted-foreground hover:text-primary"
                                                    onClick={() => replaceAutoQuestionMutation.mutate(q.id)}
                                                    disabled={replaceAutoQuestionMutation.isPending}
                                                    title="Replace with another question"
                                                >
                                                    <RefreshCw className={`w-3.5 h-3.5 ${replaceAutoQuestionMutation.isPending ? 'animate-spin' : ''}`} />
                                                </Button>
                                                <Button
                                                    variant="ghost" size="sm"
                                                    className="h-7 w-7 p-0 text-muted-foreground hover:text-red-600"
                                                    onClick={() => removeAutoQuestion(q.id)}
                                                    title="Remove question"
                                                >
                                                    <XCircle className="w-3.5 h-3.5" />
                                                </Button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Empty state when no questions generated yet */}
                        {autoGeneratedQuestions.length === 0 && !autoGenerateMutation.isPending && (
                            <div className="border rounded-lg p-8 text-center">
                                <Wand2 className="w-10 h-10 mx-auto mb-3 text-violet-300 dark:text-violet-700" />
                                <p className="text-sm text-muted-foreground">Configure your filters above and click <strong>Generate Questions</strong></p>
                                <p className="text-xs text-muted-foreground mt-1">Questions will be randomly selected from your Question Bank</p>
                            </div>
                        )}

                        {/* Action Buttons */}
                        <div className="flex justify-end gap-2">
                            <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                            <Button
                                onClick={() => importAutoGeneratedMutation.mutate(autoGeneratedQuestions.map((q: any) => q.id))}
                                disabled={autoGeneratedQuestions.length === 0 || importAutoGeneratedMutation.isPending}
                                className="bg-primary hover:bg-primary/90 text-white"
                            >
                                {importAutoGeneratedMutation.isPending
                                    ? <><Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> Importing...</>
                                    : `Import ${autoGeneratedQuestions.length} Question${autoGeneratedQuestions.length !== 1 ? 's' : ''} to Exam`
                                }
                            </Button>
                        </div>
                    </TabsContent>
                </Tabs>
            </DialogContent>
        </Dialog>
    );
}
