/**
 * Nigerian Secondary & Primary School Curriculum Seed Data
 * Sources: scholarclopedia.com/ng, syllabus.ng
 *
 * Covers: Primary 1–6, JSS 1–3, SS1–SS3
 * All templates start as published=false (Super Admin must review & publish)
 */

import { db } from "./storage";
import { curriculumTemplates, curriculumTemplateTopics } from "@shared/schema.pg";
import { eq } from "drizzle-orm";

interface TemplateDef {
  title: string;
  level: "primary" | "jss" | "ss" | "custom";
  className: string;
  subjectName: string;
  description: string;
  topics: { term: "first" | "second" | "third"; week: number; name: string; description?: string }[];
}

const TEMPLATES: TemplateDef[] = [
  // ═══════════════════════════════════════════════════════════════════
  // JSS 1
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "JSS 1 – English Language",
    level: "jss", className: "JSS 1", subjectName: "English Language",
    description: "Comprehensive English Language scheme covering grammar, comprehension, composition and literature for JSS 1.",
    topics: [
      { term: "first", week: 1, name: "Introduction: Parts of Speech – Nouns" },
      { term: "first", week: 1, name: "Comprehension: Reading for Meaning" },
      { term: "first", week: 2, name: "Parts of Speech – Pronouns and Adjectives" },
      { term: "first", week: 2, name: "Vocabulary: Word Formation" },
      { term: "first", week: 3, name: "Verbs – Types and Usage" },
      { term: "first", week: 3, name: "Sentence Construction: Simple Sentences" },
      { term: "first", week: 4, name: "Adverbs and Prepositions" },
      { term: "first", week: 4, name: "Comprehension: Inference and Deduction" },
      { term: "first", week: 5, name: "Conjunctions and Interjections" },
      { term: "first", week: 5, name: "Composition: Letter Writing (Informal)" },
      { term: "first", week: 6, name: "Tenses: Present and Past Tense" },
      { term: "first", week: 7, name: "Tenses: Future Tense and Continuous Aspect" },
      { term: "first", week: 8, name: "Direct and Indirect Speech" },
      { term: "first", week: 9, name: "Punctuation Marks and Their Uses" },
      { term: "first", week: 10, name: "Essay Writing: Narrative Essay" },
      { term: "first", week: 11, name: "Diphthongs and Vowel Sounds" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Reading: Skimming and Scanning Techniques" },
      { term: "second", week: 2, name: "Subject-Verb Agreement" },
      { term: "second", week: 3, name: "Synonyms, Antonyms and Homonyms" },
      { term: "second", week: 4, name: "Descriptive Essay Writing" },
      { term: "second", week: 5, name: "Passive and Active Voice" },
      { term: "second", week: 6, name: "Question Tags" },
      { term: "second", week: 7, name: "Formal Letter Writing" },
      { term: "second", week: 8, name: "Comprehension: Poetry Appreciation" },
      { term: "second", week: 9, name: "Figures of Speech: Simile and Metaphor" },
      { term: "second", week: 10, name: "Argumentative Essay Writing" },
      { term: "second", week: 11, name: "Stress and Intonation Patterns" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Expository Essay Writing" },
      { term: "third", week: 2, name: "Conditional Sentences (If Clauses)" },
      { term: "third", week: 3, name: "Idiomatic Expressions" },
      { term: "third", week: 4, name: "Comprehension Passages – Summary Writing" },
      { term: "third", week: 5, name: "Clauses: Main and Subordinate Clauses" },
      { term: "third", week: 6, name: "Report Writing" },
      { term: "third", week: 7, name: "Dialogue and Conversation Writing" },
      { term: "third", week: 8, name: "Revision – Grammar and Composition" },
      { term: "third", week: 9, name: "Examination Revision" },
    ],
  },

  {
    title: "JSS 1 – Mathematics",
    level: "jss", className: "JSS 1", subjectName: "Mathematics",
    description: "JSS 1 Mathematics covering whole numbers, fractions, basic geometry, and introductory algebra.",
    topics: [
      { term: "first", week: 1, name: "Whole Numbers: Counting and Place Value" },
      { term: "first", week: 2, name: "Whole Numbers: Addition and Subtraction" },
      { term: "first", week: 3, name: "Multiplication and Division of Whole Numbers" },
      { term: "first", week: 4, name: "Factors and Multiples" },
      { term: "first", week: 5, name: "LCM and HCF" },
      { term: "first", week: 6, name: "Fractions: Types and Equivalent Fractions" },
      { term: "first", week: 7, name: "Addition and Subtraction of Fractions" },
      { term: "first", week: 8, name: "Multiplication and Division of Fractions" },
      { term: "first", week: 9, name: "Decimals: Conversion and Operations" },
      { term: "first", week: 10, name: "Percentages: Basic Concepts" },
      { term: "first", week: 11, name: "Ratio and Proportion" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Indices: Laws of Indices" },
      { term: "second", week: 2, name: "Standard Form (Scientific Notation)" },
      { term: "second", week: 3, name: "Approximation: Significant Figures and Decimal Places" },
      { term: "second", week: 4, name: "Algebraic Expressions: Simplification" },
      { term: "second", week: 5, name: "Simple Equations: Linear Equations in One Variable" },
      { term: "second", week: 6, name: "Word Problems Involving Linear Equations" },
      { term: "second", week: 7, name: "Basic Geometry: Points, Lines and Angles" },
      { term: "second", week: 8, name: "Types of Angles and Angle Properties" },
      { term: "second", week: 9, name: "Triangles: Properties and Types" },
      { term: "second", week: 10, name: "Quadrilaterals and Polygons" },
      { term: "second", week: 11, name: "Perimeter and Area of Plane Shapes" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Circle: Circumference and Area" },
      { term: "third", week: 2, name: "Statistics: Data Collection and Presentation" },
      { term: "third", week: 3, name: "Frequency Tables and Bar Charts" },
      { term: "third", week: 4, name: "Pie Charts" },
      { term: "third", week: 5, name: "Mean, Median and Mode" },
      { term: "third", week: 6, name: "Directed Numbers (Integers)" },
      { term: "third", week: 7, name: "Number Bases: Binary and Octal" },
      { term: "third", week: 8, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 1 – Basic Science",
    level: "jss", className: "JSS 1", subjectName: "Basic Science",
    description: "Basic Science for JSS 1 covering living things, matter, energy, and the environment.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Science: Scientific Method" },
      { term: "first", week: 2, name: "Living Things: Characteristics of Living Things" },
      { term: "first", week: 3, name: "Classification of Living Things" },
      { term: "first", week: 4, name: "The Cell: Structure and Functions" },
      { term: "first", week: 5, name: "Plant and Animal Cells" },
      { term: "first", week: 6, name: "Matter: States of Matter" },
      { term: "first", week: 7, name: "Properties of Solids, Liquids and Gases" },
      { term: "first", week: 8, name: "Separation of Mixtures: Filtering and Evaporation" },
      { term: "first", week: 9, name: "Separation: Distillation and Chromatography" },
      { term: "first", week: 10, name: "Pure Substances and Mixtures" },
      { term: "first", week: 11, name: "Laboratory Safety Rules and Equipment" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Energy: Forms of Energy" },
      { term: "second", week: 2, name: "Heat Energy: Sources and Effects" },
      { term: "second", week: 3, name: "Light Energy: Sources and Reflection" },
      { term: "second", week: 4, name: "Sound Energy: Propagation and Properties" },
      { term: "second", week: 5, name: "Electrical Energy: Simple Circuits" },
      { term: "second", week: 6, name: "Nutrition in Humans: Food and Nutrients" },
      { term: "second", week: 7, name: "Food Tests: Starch, Protein, Fat and Sugar" },
      { term: "second", week: 8, name: "Digestive System" },
      { term: "second", week: 9, name: "Reproductive System – Introduction" },
      { term: "second", week: 10, name: "Personal Hygiene and Health" },
      { term: "second", week: 11, name: "Diseases: Causes, Prevention and Control" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "The Environment: Components of the Environment" },
      { term: "third", week: 2, name: "Ecosystem: Food Chains and Food Webs" },
      { term: "third", week: 3, name: "Soil: Types and Properties" },
      { term: "third", week: 4, name: "Air and Water Pollution" },
      { term: "third", week: 5, name: "Conservation of Natural Resources" },
      { term: "third", week: 6, name: "Simple Machines: Types and Uses" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 1 – Social Studies",
    level: "jss", className: "JSS 1", subjectName: "Social Studies",
    description: "Social Studies for JSS 1 covering culture, family, community, and citizenship.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Social Studies" },
      { term: "first", week: 2, name: "The Family: Types and Functions" },
      { term: "first", week: 3, name: "Family Values and Responsibilities" },
      { term: "first", week: 4, name: "Marriage: Types and Processes" },
      { term: "first", week: 5, name: "Culture: Meaning and Elements" },
      { term: "first", week: 6, name: "Nigerian Cultures and Traditions" },
      { term: "first", week: 7, name: "Cultural Practices: Positive and Negative" },
      { term: "first", week: 8, name: "Communication: Types and Importance" },
      { term: "first", week: 9, name: "Transportation: Types and Importance" },
      { term: "first", week: 10, name: "Trade and Commerce in Nigeria" },
      { term: "first", week: 11, name: "Media and Their Role in Society" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "The Community: Types of Community" },
      { term: "second", week: 2, name: "Community Services and Development" },
      { term: "second", week: 3, name: "Government: Meaning and Purposes" },
      { term: "second", week: 4, name: "Types of Government" },
      { term: "second", week: 5, name: "Citizenship: Rights and Duties" },
      { term: "second", week: 6, name: "Social Problems: Causes and Solutions" },
      { term: "second", week: 7, name: "Drugs and Drug Abuse" },
      { term: "second", week: 8, name: "Environmental Problems in Nigeria" },
      { term: "second", week: 9, name: "Population and Its Effects" },
      { term: "second", week: 10, name: "National Symbols and Their Importance" },
      { term: "second", week: 11, name: "Inter-Ethnic Relations in Nigeria" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "The Economy: Resources and Production" },
      { term: "third", week: 2, name: "Human Needs: Basic and Secondary" },
      { term: "third", week: 3, name: "Poverty and Its Effects" },
      { term: "third", week: 4, name: "Globalisation and Its Effects on Nigeria" },
      { term: "third", week: 5, name: "Human Rights and Child Rights" },
      { term: "third", week: 6, name: "Conflict Resolution and Peacebuilding" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 1 – Computer Studies",
    level: "jss", className: "JSS 1", subjectName: "Computer Studies",
    description: "Introduction to computing for JSS 1 covering hardware, software, and basic operations.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Computers: History and Generations" },
      { term: "first", week: 2, name: "Components of a Computer System" },
      { term: "first", week: 3, name: "Hardware: Input and Output Devices" },
      { term: "first", week: 4, name: "Storage Devices: Primary and Secondary" },
      { term: "first", week: 5, name: "Software: System and Application Software" },
      { term: "first", week: 6, name: "Operating Systems: Functions and Examples" },
      { term: "first", week: 7, name: "Booting and Shutting Down a Computer" },
      { term: "first", week: 8, name: "Files and Folders: Creating and Managing" },
      { term: "first", week: 9, name: "The Keyboard: Types and Key Functions" },
      { term: "first", week: 10, name: "The Mouse and Touch Pad" },
      { term: "first", week: 11, name: "Word Processing: Introduction to MS Word" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Microsoft Word: Formatting Text" },
      { term: "second", week: 2, name: "Microsoft Word: Inserting Tables and Images" },
      { term: "second", week: 3, name: "Spreadsheet: Introduction to MS Excel" },
      { term: "second", week: 4, name: "MS Excel: Entering Data and Basic Formulas" },
      { term: "second", week: 5, name: "Presentation Software: Introduction to PowerPoint" },
      { term: "second", week: 6, name: "Internet: Meaning, Uses and Safety" },
      { term: "second", week: 7, name: "Email: Sending and Receiving" },
      { term: "second", week: 8, name: "Search Engines and Browsing" },
      { term: "second", week: 9, name: "Social Media: Benefits and Dangers" },
      { term: "second", week: 10, name: "Cyberbullying and Online Safety" },
      { term: "second", week: 11, name: "Computer Viruses and Antivirus" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Number Systems: Binary and Denary" },
      { term: "third", week: 2, name: "Binary Arithmetic: Addition and Subtraction" },
      { term: "third", week: 3, name: "Introduction to Programming: Algorithms" },
      { term: "third", week: 4, name: "Flowcharts and Pseudocode" },
      { term: "third", week: 5, name: "Introduction to Scratch Programming" },
      { term: "third", week: 6, name: "Scratch: Creating Simple Animations" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 1 – Civic Education",
    level: "jss", className: "JSS 1", subjectName: "Civic Education",
    description: "Civic Education for JSS 1 on democratic values, citizenship, and civic responsibilities.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Civic Education" },
      { term: "first", week: 2, name: "Values: Meaning and Types of Values" },
      { term: "first", week: 3, name: "Integrity and National Values" },
      { term: "first", week: 4, name: "Democracy: Meaning and Features" },
      { term: "first", week: 5, name: "Human Rights: Meaning and Types" },
      { term: "first", week: 6, name: "Child Rights Act" },
      { term: "first", week: 7, name: "Drug Abuse: Effects on Youths" },
      { term: "first", week: 8, name: "Traffic Regulations and Road Safety" },
      { term: "first", week: 9, name: "Nationalism and Patriotism" },
      { term: "first", week: 10, name: "National Symbols of Nigeria" },
      { term: "first", week: 11, name: "Civic Responsibilities of Citizens" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Constitutionalism and Rule of Law" },
      { term: "second", week: 2, name: "Electoral Process in Nigeria" },
      { term: "second", week: 3, name: "Independent National Electoral Commission (INEC)" },
      { term: "second", week: 4, name: "Good Governance: Characteristics" },
      { term: "second", week: 5, name: "Corruption and Anti-Corruption Agencies" },
      { term: "second", week: 6, name: "Gender Equality and Social Justice" },
      { term: "second", week: 7, name: "Environmental Citizenship" },
      { term: "second", week: 8, name: "Conflict Resolution in the Community" },
      { term: "second", week: 9, name: "Federalism in Nigeria" },
      { term: "second", week: 10, name: "Local Government Administration" },
      { term: "second", week: 11, name: "Citizenship and Civic Education Review" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Social Vices and Their Effects" },
      { term: "third", week: 2, name: "HIV/AIDS: Prevention and Stigma" },
      { term: "third", week: 3, name: "Volunteerism and Community Service" },
      { term: "third", week: 4, name: "Leadership: Qualities and Types" },
      { term: "third", week: 5, name: "International Organisations (UN, AU, ECOWAS)" },
      { term: "third", week: 6, name: "Nigeria's Role in International Affairs" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // JSS 2
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "JSS 2 – Mathematics",
    level: "jss", className: "JSS 2", subjectName: "Mathematics",
    description: "JSS 2 Mathematics covering algebra, geometry, statistics, and commercial arithmetic.",
    topics: [
      { term: "first", week: 1, name: "Expansion and Simplification of Algebraic Expressions" },
      { term: "first", week: 2, name: "Factorisation of Algebraic Expressions" },
      { term: "first", week: 3, name: "Linear Equations in Two Variables" },
      { term: "first", week: 4, name: "Simultaneous Linear Equations: Elimination Method" },
      { term: "first", week: 5, name: "Simultaneous Linear Equations: Substitution Method" },
      { term: "first", week: 6, name: "Linear Inequalities" },
      { term: "first", week: 7, name: "Graphs of Linear Equations" },
      { term: "first", week: 8, name: "Gradient and Intercept" },
      { term: "first", week: 9, name: "Plane Figures: Properties of Triangles" },
      { term: "first", week: 10, name: "Congruency and Similarity" },
      { term: "first", week: 11, name: "Pythagoras Theorem" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Surface Area of Cuboid and Cube" },
      { term: "second", week: 2, name: "Volume of Cuboid and Cube" },
      { term: "second", week: 3, name: "Cylinder: Surface Area and Volume" },
      { term: "second", week: 4, name: "Profit and Loss" },
      { term: "second", week: 5, name: "Simple Interest" },
      { term: "second", week: 6, name: "Percentage, Discount and Commission" },
      { term: "second", week: 7, name: "Scales and Scale Drawing" },
      { term: "second", week: 8, name: "Bearing and Direction" },
      { term: "second", week: 9, name: "Trigonometry: Sine, Cosine and Tangent" },
      { term: "second", week: 10, name: "Trigonometric Ratios: Solving Triangles" },
      { term: "second", week: 11, name: "Sets: Types and Notation" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Venn Diagrams: Two Sets" },
      { term: "third", week: 2, name: "Venn Diagrams: Three Sets and Problems" },
      { term: "third", week: 3, name: "Statistics: Grouped Data and Frequency Tables" },
      { term: "third", week: 4, name: "Histograms and Frequency Polygons" },
      { term: "third", week: 5, name: "Cumulative Frequency: Ogive" },
      { term: "third", week: 6, name: "Probability: Basic Concepts" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 2 – Basic Science",
    level: "jss", className: "JSS 2", subjectName: "Basic Science",
    description: "JSS 2 Basic Science covering atoms, chemical reactions, forces, and human biology.",
    topics: [
      { term: "first", week: 1, name: "Atoms and Molecules: Structure of the Atom" },
      { term: "first", week: 2, name: "Elements, Compounds and Mixtures" },
      { term: "first", week: 3, name: "Periodic Table: Groups and Periods" },
      { term: "first", week: 4, name: "Chemical Reactions: Types and Equations" },
      { term: "first", week: 5, name: "Acids, Bases and Salts" },
      { term: "first", week: 6, name: "Metals and Non-Metals" },
      { term: "first", week: 7, name: "Carbon and Its Compounds" },
      { term: "first", week: 8, name: "Forces: Types and Effects" },
      { term: "first", week: 9, name: "Motion: Speed, Velocity and Acceleration" },
      { term: "first", week: 10, name: "Newton's Laws of Motion" },
      { term: "first", week: 11, name: "Work, Energy and Power" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Reproduction in Plants" },
      { term: "second", week: 2, name: "Reproduction in Animals" },
      { term: "second", week: 3, name: "Human Reproductive System" },
      { term: "second", week: 4, name: "Puberty and Adolescence" },
      { term: "second", week: 5, name: "Sexually Transmitted Infections" },
      { term: "second", week: 6, name: "The Respiratory System" },
      { term: "second", week: 7, name: "The Circulatory System" },
      { term: "second", week: 8, name: "The Skeletal System" },
      { term: "second", week: 9, name: "Sense Organs and the Nervous System" },
      { term: "second", week: 10, name: "The Excretory System" },
      { term: "second", week: 11, name: "Ecology: Habitats and Biomes" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Electricity: Current, Voltage and Resistance" },
      { term: "third", week: 2, name: "Ohm's Law and Simple Circuits" },
      { term: "third", week: 3, name: "Magnetism and Electromagnetism" },
      { term: "third", week: 4, name: "Waves: Properties and Types" },
      { term: "third", week: 5, name: "Technology and Society: ICT and Health" },
      { term: "third", week: 6, name: "Space Science: Solar System" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "JSS 2 – English Language",
    level: "jss", className: "JSS 2", subjectName: "English Language",
    description: "JSS 2 English Language with advanced grammar, comprehension, and various essay types.",
    topics: [
      { term: "first", week: 1, name: "Nouns: Countable and Uncountable Nouns" },
      { term: "first", week: 2, name: "Pronouns: Relative and Reflexive Pronouns" },
      { term: "first", week: 3, name: "Tenses: Perfect and Perfect Continuous" },
      { term: "first", week: 4, name: "Modal Verbs: Can, Could, May, Might" },
      { term: "first", week: 5, name: "Comprehension: Identifying Main Ideas" },
      { term: "first", week: 6, name: "Essay Writing: Descriptive Essay" },
      { term: "first", week: 7, name: "Phrases: Noun, Verb and Prepositional Phrases" },
      { term: "first", week: 8, name: "Clauses: Defining and Non-defining" },
      { term: "first", week: 9, name: "Reported Speech" },
      { term: "first", week: 10, name: "Expository Essay Writing" },
      { term: "first", week: 11, name: "Phonetics: Consonant Clusters" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Comprehension and Summary Writing" },
      { term: "second", week: 2, name: "Argumentative Essay" },
      { term: "second", week: 3, name: "Persuasive Writing Techniques" },
      { term: "second", week: 4, name: "Register and Varieties of English" },
      { term: "second", week: 5, name: "Figures of Speech: Personification and Irony" },
      { term: "second", week: 6, name: "Speech Writing and Oral Presentation" },
      { term: "second", week: 7, name: "Report Writing: School and Formal Reports" },
      { term: "second", week: 8, name: "Minutes of Meeting" },
      { term: "second", week: 9, name: "Poetry: Structure and Appreciation" },
      { term: "second", week: 10, name: "Drama: Reading and Appreciation" },
      { term: "second", week: 11, name: "Prose Fiction: Plot and Character Analysis" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Punctuation: Advanced Usage" },
      { term: "third", week: 2, name: "Formal and Informal Register" },
      { term: "third", week: 3, name: "Debate: Organising Arguments" },
      { term: "third", week: 4, name: "Comprehension: Tone and Mood" },
      { term: "third", week: 5, name: "Creative Writing: Short Story" },
      { term: "third", week: 6, name: "Exam Revision: Grammar Review" },
      { term: "third", week: 7, name: "Examination Revision" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // JSS 3
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "JSS 3 – Mathematics",
    level: "jss", className: "JSS 3", subjectName: "Mathematics",
    description: "JSS 3 Mathematics preparing students for BECE with algebra, geometry, and statistics.",
    topics: [
      { term: "first", week: 1, name: "Quadratic Expressions: Expansion and Factorisation" },
      { term: "first", week: 2, name: "Solving Quadratic Equations by Factorisation" },
      { term: "first", week: 3, name: "Graphs of Quadratic Functions" },
      { term: "first", week: 4, name: "Linear and Quadratic Inequalities" },
      { term: "first", week: 5, name: "Indices and Logarithms" },
      { term: "first", week: 6, name: "Matrices: Types and Operations" },
      { term: "first", week: 7, name: "Determinants and Inverse of 2×2 Matrices" },
      { term: "first", week: 8, name: "Circle Theorems: Angles in Circles" },
      { term: "first", week: 9, name: "Tangents and Chords" },
      { term: "first", week: 10, name: "Transformation: Reflection and Translation" },
      { term: "first", week: 11, name: "Transformation: Rotation and Enlargement" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Simultaneous Equations: Linear and Quadratic" },
      { term: "second", week: 2, name: "Mensuration: Prisms and Pyramids" },
      { term: "second", week: 3, name: "Sphere and Cone: Volume and Surface Area" },
      { term: "second", week: 4, name: "Commercial Arithmetic: Compound Interest" },
      { term: "second", week: 5, name: "Hire Purchase and Mortgage" },
      { term: "second", week: 6, name: "Tax and VAT" },
      { term: "second", week: 7, name: "Vectors: Addition and Subtraction" },
      { term: "second", week: 8, name: "Vectors: Magnitude and Direction" },
      { term: "second", week: 9, name: "Statistics: Measures of Dispersion" },
      { term: "second", week: 10, name: "Probability: Combined Events" },
      { term: "second", week: 11, name: "Locus: Definition and Construction" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "BECE Revision: Number and Numeration" },
      { term: "third", week: 2, name: "BECE Revision: Algebra" },
      { term: "third", week: 3, name: "BECE Revision: Geometry" },
      { term: "third", week: 4, name: "BECE Revision: Statistics and Probability" },
      { term: "third", week: 5, name: "BECE Practice: Past Questions and Model Answers" },
      { term: "third", week: 6, name: "BECE Examination Preparation" },
    ],
  },

  {
    title: "JSS 3 – English Language",
    level: "jss", className: "JSS 3", subjectName: "English Language",
    description: "JSS 3 English preparing for BECE with all four language skills.",
    topics: [
      { term: "first", week: 1, name: "Advanced Grammar: Complex and Compound Sentences" },
      { term: "first", week: 2, name: "Comprehension and Summary (BECE Style)" },
      { term: "first", week: 3, name: "Essay Writing: Narrative and Descriptive" },
      { term: "first", week: 4, name: "Letter Writing: Formal, Semi-formal, Informal" },
      { term: "first", week: 5, name: "Idioms and Proverbs" },
      { term: "first", week: 6, name: "Oral English: Vowels and Consonants" },
      { term: "first", week: 7, name: "Active and Passive Voice: Advanced" },
      { term: "first", week: 8, name: "Reported Speech: Advanced Tense Shifts" },
      { term: "first", week: 9, name: "Concord: Subject-Verb Agreement (Advanced)" },
      { term: "first", week: 10, name: "Register and Style in English" },
      { term: "first", week: 11, name: "BECE Past Question Review – Language" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Literature: Poetry Analysis" },
      { term: "second", week: 2, name: "Literature: Drama and Prose" },
      { term: "second", week: 3, name: "Argumentative and Expository Essays" },
      { term: "second", week: 4, name: "Comprehension: Inference, Tone and Attitude" },
      { term: "second", week: 5, name: "Speech Work: Stress and Rhythm" },
      { term: "second", week: 6, name: "Vocabulary Development: Synonyms, Antonyms" },
      { term: "second", week: 7, name: "Figures of Speech: Complete Review" },
      { term: "second", week: 8, name: "BECE Past Questions: Comprehension" },
      { term: "second", week: 9, name: "BECE Past Questions: Essay Writing" },
      { term: "second", week: 10, name: "BECE Past Questions: Oral English" },
      { term: "second", week: 11, name: "BECE Intensive Revision" },
      { term: "second", week: 12, name: "Mock Examination" },

      { term: "third", week: 1, name: "BECE Final Preparation: Language Skills" },
      { term: "third", week: 2, name: "BECE Final Preparation: Literature" },
      { term: "third", week: 3, name: "BECE Final Practice – Full Paper" },
      { term: "third", week: 4, name: "BECE Examination" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // SS 1
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "SS 1 – Mathematics",
    level: "ss", className: "SS 1", subjectName: "Mathematics",
    description: "SS 1 Mathematics covering further algebra, trigonometry, coordinate geometry, and statistics.",
    topics: [
      { term: "first", week: 1, name: "Surds: Simplification and Operations" },
      { term: "first", week: 2, name: "Indices and Logarithms: Advanced" },
      { term: "first", week: 3, name: "Polynomials: Operations and Remainder Theorem" },
      { term: "first", week: 4, name: "Algebraic Fractions: Simplification" },
      { term: "first", week: 5, name: "Simultaneous Equations: Three Unknowns" },
      { term: "first", week: 6, name: "Quadratic Equations: Completing the Square" },
      { term: "first", week: 7, name: "Quadratic Equations: Quadratic Formula" },
      { term: "first", week: 8, name: "Quadratic Inequalities" },
      { term: "first", week: 9, name: "Permutation and Combination" },
      { term: "first", week: 10, name: "Binomial Theorem" },
      { term: "first", week: 11, name: "Sequence and Series: AP and GP" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Trigonometry: Radian Measure" },
      { term: "second", week: 2, name: "Trigonometric Identities" },
      { term: "second", week: 3, name: "Graphs of Trigonometric Functions" },
      { term: "second", week: 4, name: "Coordinate Geometry: Distance and Midpoint" },
      { term: "second", week: 5, name: "Straight Line: Equation of a Line" },
      { term: "second", week: 6, name: "Circle: Equation and Properties" },
      { term: "second", week: 7, name: "Differentiation: Rules and Applications" },
      { term: "second", week: 8, name: "Integration: Basic Rules" },
      { term: "second", week: 9, name: "Matrices and Determinants" },
      { term: "second", week: 10, name: "Vectors: 3D and Applications" },
      { term: "second", week: 11, name: "Statistics: Grouped Data and Quartiles" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Probability: Conditional Probability" },
      { term: "third", week: 2, name: "Probability Distributions: Binomial" },
      { term: "third", week: 3, name: "Loci: Construction and Applications" },
      { term: "third", week: 4, name: "Mensuration: Advanced Surface Area and Volume" },
      { term: "third", week: 5, name: "Graphs: Interpreting and Sketching Curves" },
      { term: "third", week: 6, name: "Revision: WAEC/NECO Topics Overview" },
      { term: "third", week: 7, name: "Examination Revision" },
    ],
  },

  {
    title: "SS 1 – English Language",
    level: "ss", className: "SS 1", subjectName: "English Language",
    description: "SS 1 English Language with advanced grammar, essay types, oral English and literature.",
    topics: [
      { term: "first", week: 1, name: "Parts of Speech: Advanced Review" },
      { term: "first", week: 2, name: "Sentence Types and Structures" },
      { term: "first", week: 3, name: "Essay Writing: Formal Letter" },
      { term: "first", week: 4, name: "Essay Writing: Narrative Essay" },
      { term: "first", week: 5, name: "Comprehension: WAEC-Style Passages" },
      { term: "first", week: 6, name: "Summary Writing Techniques" },
      { term: "first", week: 7, name: "Oral English: Vowels and Consonant Sounds" },
      { term: "first", week: 8, name: "Oral English: Stress Patterns" },
      { term: "first", week: 9, name: "Figures of Speech: Comprehensive Review" },
      { term: "first", week: 10, name: "Idioms: Common Nigerian and International" },
      { term: "first", week: 11, name: "Argumentative Essay" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Concord: Advanced Subject-Verb Agreement" },
      { term: "second", week: 2, name: "Essay Writing: Descriptive Essay" },
      { term: "second", week: 3, name: "Essay Writing: Expository Essay" },
      { term: "second", week: 4, name: "Literature: Introduction to Prose Fiction" },
      { term: "second", week: 5, name: "Literature: Character and Theme Analysis" },
      { term: "second", week: 6, name: "Literature: Poetry – Devices and Meaning" },
      { term: "second", week: 7, name: "Literature: Drama – Plot and Conflict" },
      { term: "second", week: 8, name: "Vocabulary: Collocations and Phrasal Verbs" },
      { term: "second", week: 9, name: "Register: Legal, Medical and Scientific English" },
      { term: "second", week: 10, name: "Speech Writing and Debate" },
      { term: "second", week: 11, name: "Reading Comprehension: Speed and Accuracy" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Informal Letter and Note Writing" },
      { term: "third", week: 2, name: "Report Writing: Committee and Annual Reports" },
      { term: "third", week: 3, name: "Comprehension Practice – Timed Exercises" },
      { term: "third", week: 4, name: "Oral English: Intonation and Rhythm" },
      { term: "third", week: 5, name: "Past WAEC Questions Review – Language" },
      { term: "third", week: 6, name: "Past WAEC Questions Review – Literature" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "SS 1 – Physics",
    level: "ss", className: "SS 1", subjectName: "Physics",
    description: "SS 1 Physics covering mechanics, heat, waves, and electricity fundamentals.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Physics: Scope and Applications" },
      { term: "first", week: 2, name: "Measurements: SI Units and Dimensions" },
      { term: "first", week: 3, name: "Scalars and Vectors" },
      { term: "first", week: 4, name: "Motion: Equations of Uniformly Accelerated Motion" },
      { term: "first", week: 5, name: "Projectile Motion" },
      { term: "first", week: 6, name: "Newton's Laws of Motion" },
      { term: "first", week: 7, name: "Momentum and Impulse" },
      { term: "first", week: 8, name: "Work, Energy and Power" },
      { term: "first", week: 9, name: "Conservation of Energy" },
      { term: "first", week: 10, name: "Friction: Static and Kinetic" },
      { term: "first", week: 11, name: "Simple Machines and Mechanical Advantage" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Pressure in Fluids: Pascal's Principle" },
      { term: "second", week: 2, name: "Archimedes' Principle and Flotation" },
      { term: "second", week: 3, name: "Temperature and Heat" },
      { term: "second", week: 4, name: "Thermal Expansion of Solids, Liquids and Gases" },
      { term: "second", week: 5, name: "Gas Laws: Boyle's, Charles' and General Gas Law" },
      { term: "second", week: 6, name: "Heat Capacity and Specific Heat Capacity" },
      { term: "second", week: 7, name: "Latent Heat and Changes of State" },
      { term: "second", week: 8, name: "Wave Motion: Types and Properties" },
      { term: "second", week: 9, name: "Sound Waves: Propagation and Speed" },
      { term: "second", week: 10, name: "Light: Reflection and Refraction" },
      { term: "second", week: 11, name: "Lenses and Optical Instruments" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Electrostatics: Charges and Coulomb's Law" },
      { term: "third", week: 2, name: "Electric Fields and Potentials" },
      { term: "third", week: 3, name: "Capacitors: Types and Capacitance" },
      { term: "third", week: 4, name: "Current Electricity: Ohm's Law" },
      { term: "third", week: 5, name: "Resistors: Series and Parallel" },
      { term: "third", week: 6, name: "Electrolysis: Faraday's Laws" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "SS 1 – Chemistry",
    level: "ss", className: "SS 1", subjectName: "Chemistry",
    description: "SS 1 Chemistry covering atomic structure, bonding, stoichiometry, and reactions.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Chemistry: Scope and Importance" },
      { term: "first", week: 2, name: "Atomic Structure: Protons, Neutrons and Electrons" },
      { term: "first", week: 3, name: "Electronic Configuration and the Periodic Table" },
      { term: "first", week: 4, name: "Chemical Bonding: Ionic Bond" },
      { term: "first", week: 5, name: "Chemical Bonding: Covalent and Metallic Bonds" },
      { term: "first", week: 6, name: "Chemical Formulae and Nomenclature" },
      { term: "first", week: 7, name: "Chemical Equations and Balancing" },
      { term: "first", week: 8, name: "Stoichiometry: Mole Concept" },
      { term: "first", week: 9, name: "Stoichiometry: Mass-Mass and Mass-Volume Calculations" },
      { term: "first", week: 10, name: "States of Matter: Gas Laws" },
      { term: "first", week: 11, name: "Solutions: Concentration Calculations" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Acids, Bases and Salts: Properties and Reactions" },
      { term: "second", week: 2, name: "pH Scale and Indicators" },
      { term: "second", week: 3, name: "Preparation of Salts" },
      { term: "second", week: 4, name: "Qualitative Analysis of Cations and Anions" },
      { term: "second", week: 5, name: "Electrochemistry: Electrolysis" },
      { term: "second", week: 6, name: "Electrochemical Cells" },
      { term: "second", week: 7, name: "Kinetics: Rate of Chemical Reaction" },
      { term: "second", week: 8, name: "Equilibrium: Le Chatelier's Principle" },
      { term: "second", week: 9, name: "Oxidation and Reduction (Redox)" },
      { term: "second", week: 10, name: "Metals: Reactivity Series and Extraction" },
      { term: "second", week: 11, name: "Iron and Steel: Extraction and Uses" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Carbon and Its Compounds: Allotropes" },
      { term: "third", week: 2, name: "Organic Chemistry: Introduction and Hydrocarbons" },
      { term: "third", week: 3, name: "Alkanes, Alkenes and Alkynes" },
      { term: "third", week: 4, name: "Petroleum: Fractional Distillation" },
      { term: "third", week: 5, name: "Polymers: Addition and Condensation Polymerisation" },
      { term: "third", week: 6, name: "Environmental Chemistry: Pollution" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "SS 1 – Biology",
    level: "ss", className: "SS 1", subjectName: "Biology",
    description: "SS 1 Biology covering cell biology, ecology, genetics foundations, and organ systems.",
    topics: [
      { term: "first", week: 1, name: "Cell Biology: Prokaryotic and Eukaryotic Cells" },
      { term: "first", week: 2, name: "Cell Organelles and Their Functions" },
      { term: "first", week: 3, name: "Diffusion and Osmosis" },
      { term: "first", week: 4, name: "Active Transport and Plasmolysis" },
      { term: "first", week: 5, name: "Photosynthesis: Light and Dark Reactions" },
      { term: "first", week: 6, name: "Respiration: Aerobic and Anaerobic" },
      { term: "first", week: 7, name: "Feeding: Autotrophs and Heterotrophs" },
      { term: "first", week: 8, name: "Digestion in Humans and Animals" },
      { term: "first", week: 9, name: "Absorption and Assimilation of Food" },
      { term: "first", week: 10, name: "Transport System in Plants: Xylem and Phloem" },
      { term: "first", week: 11, name: "Circulatory System in Humans" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Excretion: Organs and Products" },
      { term: "second", week: 2, name: "The Kidney: Structure and Function" },
      { term: "second", week: 3, name: "Osmoregulation" },
      { term: "second", week: 4, name: "Nervous System: Neurons and Impulses" },
      { term: "second", week: 5, name: "The Brain and Spinal Cord" },
      { term: "second", week: 6, name: "Endocrine System: Hormones and Glands" },
      { term: "second", week: 7, name: "Reproduction in Plants: Pollination and Fertilisation" },
      { term: "second", week: 8, name: "Reproduction in Animals: Types and Strategies" },
      { term: "second", week: 9, name: "Human Reproduction and Development" },
      { term: "second", week: 10, name: "Ecology: Populations and Communities" },
      { term: "second", week: 11, name: "Food Webs and Energy Flow" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Variation: Continuous and Discontinuous" },
      { term: "third", week: 2, name: "Genetics: Mendel's Laws" },
      { term: "third", week: 3, name: "Genetics: Monohybrid and Dihybrid Crosses" },
      { term: "third", week: 4, name: "DNA and Protein Synthesis" },
      { term: "third", week: 5, name: "Evolution: Darwin's Theory" },
      { term: "third", week: 6, name: "Conservation of Biodiversity" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "SS 1 – Economics",
    level: "ss", className: "SS 1", subjectName: "Economics",
    description: "SS 1 Economics covering basic economic concepts, demand, supply and market structures.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Economics: Scope and Methods" },
      { term: "first", week: 2, name: "Basic Economic Concepts: Scarcity and Choice" },
      { term: "first", week: 3, name: "Economic Systems: Capitalism, Socialism, Mixed" },
      { term: "first", week: 4, name: "Demand: Law and Determinants" },
      { term: "first", week: 5, name: "Demand: Elasticity of Demand" },
      { term: "first", week: 6, name: "Supply: Law and Determinants" },
      { term: "first", week: 7, name: "Supply: Elasticity of Supply" },
      { term: "first", week: 8, name: "Market Equilibrium: Price and Quantity" },
      { term: "first", week: 9, name: "Consumer Theory: Utility and Indifference Curves" },
      { term: "first", week: 10, name: "Production Theory: Factors of Production" },
      { term: "first", week: 11, name: "Costs and Revenue: Short Run" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Market Structures: Perfect Competition" },
      { term: "second", week: 2, name: "Monopoly and Monopolistic Competition" },
      { term: "second", week: 3, name: "Oligopoly and Duopoly" },
      { term: "second", week: 4, name: "National Income: Concepts and Measurement" },
      { term: "second", week: 5, name: "GDP, GNP and NNP" },
      { term: "second", week: 6, name: "Money: Functions and Types" },
      { term: "second", week: 7, name: "Banking: Commercial and Central Banks" },
      { term: "second", week: 8, name: "Monetary Policy in Nigeria" },
      { term: "second", week: 9, name: "Fiscal Policy: Government Revenue and Expenditure" },
      { term: "second", week: 10, name: "Taxation: Types and Principles" },
      { term: "second", week: 11, name: "Inflation: Causes and Effects" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "International Trade: Comparative Advantage" },
      { term: "third", week: 2, name: "Balance of Payments and Exchange Rates" },
      { term: "third", week: 3, name: "Economic Development and Underdevelopment" },
      { term: "third", week: 4, name: "Agriculture in Nigeria's Economy" },
      { term: "third", week: 5, name: "Industrialisation and Economic Growth" },
      { term: "third", week: 6, name: "Population and Economic Development" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  {
    title: "SS 1 – Government",
    level: "ss", className: "SS 1", subjectName: "Government",
    description: "SS 1 Government covering political concepts, constitutions, arms of government, and Nigeria's political history.",
    topics: [
      { term: "first", week: 1, name: "Introduction to Government: Meaning and Scope" },
      { term: "first", week: 2, name: "Political Concepts: State, Nation and Society" },
      { term: "first", week: 3, name: "Constitution: Types and Functions" },
      { term: "first", week: 4, name: "Democratic Principles" },
      { term: "first", week: 5, name: "The Legislature: Functions and Types" },
      { term: "first", week: 6, name: "The Executive: Types and Powers" },
      { term: "first", week: 7, name: "The Judiciary: Independence and Functions" },
      { term: "first", week: 8, name: "Separation of Powers and Checks and Balances" },
      { term: "first", week: 9, name: "Political Parties: Functions and Types" },
      { term: "first", week: 10, name: "Electoral Systems and Voting" },
      { term: "first", week: 11, name: "Public Opinion and Pressure Groups" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Federalism: Features and Practice in Nigeria" },
      { term: "second", week: 2, name: "Unitary and Confederate Systems" },
      { term: "second", week: 3, name: "Nigerian Pre-Colonial Political Systems: Hausa/Fulani" },
      { term: "second", week: 4, name: "Nigerian Pre-Colonial Political Systems: Yoruba and Igbo" },
      { term: "second", week: 5, name: "Colonial Administration in Nigeria" },
      { term: "second", week: 6, name: "Constitutional Development in Nigeria 1914–1960" },
      { term: "second", week: 7, name: "Nigeria's Independence: 1960 Constitution" },
      { term: "second", week: 8, name: "First Republic in Nigeria (1963–1966)" },
      { term: "second", week: 9, name: "Military Rule in Nigeria (1966–1979)" },
      { term: "second", week: 10, name: "Second Republic in Nigeria (1979–1983)" },
      { term: "second", week: 11, name: "The Third Republic and Transition Programmes" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Fourth Republic: 1999 Constitution" },
      { term: "third", week: 2, name: "Fundamental Human Rights in Nigeria" },
      { term: "third", week: 3, name: "Citizenship: Acquisition and Loss" },
      { term: "third", week: 4, name: "Local Government: Structure and Functions" },
      { term: "third", week: 5, name: "International Relations: Nigeria's Foreign Policy" },
      { term: "third", week: 6, name: "International Organisations: UN, AU, ECOWAS" },
      { term: "third", week: 7, name: "Revision and Examination" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // SS 2
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "SS 2 – Mathematics",
    level: "ss", className: "SS 2", subjectName: "Mathematics",
    description: "SS 2 Mathematics: advanced calculus, statistics, trigonometry, and WAEC preparation.",
    topics: [
      { term: "first", week: 1, name: "Functions: Types, Domain and Range" },
      { term: "first", week: 2, name: "Differentiation: First Principles" },
      { term: "first", week: 3, name: "Differentiation: Chain, Product and Quotient Rules" },
      { term: "first", week: 4, name: "Applications of Differentiation: Maxima and Minima" },
      { term: "first", week: 5, name: "Integration: Definite and Indefinite Integrals" },
      { term: "first", week: 6, name: "Applications of Integration: Area and Volume" },
      { term: "first", week: 7, name: "Further Trigonometry: Addition Formulae" },
      { term: "first", week: 8, name: "Trigonometric Equations" },
      { term: "first", week: 9, name: "Further Algebra: Partial Fractions" },
      { term: "first", week: 10, name: "Exponential and Logarithmic Functions" },
      { term: "first", week: 11, name: "Complex Numbers: Introduction" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Coordinate Geometry: Conic Sections" },
      { term: "second", week: 2, name: "Parametric Equations" },
      { term: "second", week: 3, name: "Numerical Methods: Iteration" },
      { term: "second", week: 4, name: "Linear Programming: Graphical Method" },
      { term: "second", week: 5, name: "Probability: Permutation and Combination" },
      { term: "second", week: 6, name: "Probability Distributions: Normal Distribution" },
      { term: "second", week: 7, name: "Inferential Statistics: Hypothesis Testing" },
      { term: "second", week: 8, name: "Correlation and Regression" },
      { term: "second", week: 9, name: "Mechanics: Statics – Forces in Equilibrium" },
      { term: "second", week: 10, name: "Mechanics: Dynamics – Projectiles" },
      { term: "second", week: 11, name: "WAEC Past Questions: Algebra and Calculus" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "WAEC Past Questions: Geometry and Trigonometry" },
      { term: "third", week: 2, name: "WAEC Past Questions: Statistics" },
      { term: "third", week: 3, name: "Mock Examination Review" },
      { term: "third", week: 4, name: "Final Revision and Examination" },
    ],
  },

  {
    title: "SS 2 – Physics",
    level: "ss", className: "SS 2", subjectName: "Physics",
    description: "SS 2 Physics: magnetism, electromagnetic induction, nuclear physics, and electronics.",
    topics: [
      { term: "first", week: 1, name: "Magnetism: Properties and Magnetic Field" },
      { term: "first", week: 2, name: "Earth's Magnetic Field and Variation" },
      { term: "first", week: 3, name: "Electromagnetic Induction: Faraday's Law" },
      { term: "first", week: 4, name: "Alternating Current: Generation and Properties" },
      { term: "first", week: 5, name: "Transformers: Step Up and Step Down" },
      { term: "first", week: 6, name: "Semiconductors: Intrinsic and Extrinsic" },
      { term: "first", week: 7, name: "Diodes: Rectification (Half and Full Wave)" },
      { term: "first", week: 8, name: "Transistors: npn and pnp Types" },
      { term: "first", week: 9, name: "Logic Gates and Boolean Algebra" },
      { term: "first", week: 10, name: "X-rays: Production and Properties" },
      { term: "first", week: 11, name: "Radioactivity: Types and Properties" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Nuclear Reactions: Fission and Fusion" },
      { term: "second", week: 2, name: "Nuclear Energy: Peaceful Uses" },
      { term: "second", week: 3, name: "Atomic Models: Thomson, Rutherford, Bohr" },
      { term: "second", week: 4, name: "Photoelectric Effect" },
      { term: "second", week: 5, name: "Wave-Particle Duality" },
      { term: "second", week: 6, name: "Gravitational Field and Potential" },
      { term: "second", week: 7, name: "Satellites and Space Science" },
      { term: "second", week: 8, name: "Simple Harmonic Motion" },
      { term: "second", week: 9, name: "Resonance and Damped Oscillations" },
      { term: "second", week: 10, name: "Interference and Diffraction of Light" },
      { term: "second", week: 11, name: "WAEC Past Questions Review" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Mock Examination: Paper 1 (Objectives)" },
      { term: "third", week: 2, name: "Mock Examination: Paper 2 (Theory)" },
      { term: "third", week: 3, name: "WAEC Past Questions: Comprehensive Review" },
      { term: "third", week: 4, name: "Final Examination Preparation" },
    ],
  },

  {
    title: "SS 2 – Chemistry",
    level: "ss", className: "SS 2", subjectName: "Chemistry",
    description: "SS 2 Chemistry: organic chemistry, thermodynamics, and qualitative analysis.",
    topics: [
      { term: "first", week: 1, name: "Organic Chemistry: Functional Groups" },
      { term: "first", week: 2, name: "Hydrocarbons: Alkanes and Cracking" },
      { term: "first", week: 3, name: "Alkenes: Addition Reactions" },
      { term: "first", week: 4, name: "Alkynes and Aromatic Hydrocarbons" },
      { term: "first", week: 5, name: "Alcohols: Types and Reactions" },
      { term: "first", week: 6, name: "Aldehydes and Ketones" },
      { term: "first", week: 7, name: "Carboxylic Acids and Esters" },
      { term: "first", week: 8, name: "Amines and Amides" },
      { term: "first", week: 9, name: "Proteins and Amino Acids" },
      { term: "first", week: 10, name: "Carbohydrates: Sugars and Starch" },
      { term: "first", week: 11, name: "Lipids: Fats and Oils" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Thermochemistry: Enthalpy Changes" },
      { term: "second", week: 2, name: "Hess's Law and Bond Energies" },
      { term: "second", week: 3, name: "Chemical Equilibrium: Kp and Kc" },
      { term: "second", week: 4, name: "Industrial Processes: Haber and Contact" },
      { term: "second", week: 5, name: "Qualitative Analysis: Salt Analysis" },
      { term: "second", week: 6, name: "Volumetric Analysis: Acid-Base Titration" },
      { term: "second", week: 7, name: "Redox Titration" },
      { term: "second", week: 8, name: "Non-Metals: Nitrogen and Its Compounds" },
      { term: "second", week: 9, name: "Sulphur and Its Compounds" },
      { term: "second", week: 10, name: "Halogens and Their Compounds" },
      { term: "second", week: 11, name: "WAEC Past Questions Review" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Comprehensive Organic Chemistry Review" },
      { term: "third", week: 2, name: "Comprehensive Physical Chemistry Review" },
      { term: "third", week: 3, name: "Mock WAEC Practical: Laboratory Techniques" },
      { term: "third", week: 4, name: "Final Examination Revision" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // SS 3
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "SS 3 – Mathematics",
    level: "ss", className: "SS 3", subjectName: "Mathematics",
    description: "SS 3 Mathematics: WAEC/NECO final preparation with comprehensive past question revision.",
    topics: [
      { term: "first", week: 1, name: "Number and Numeration: Comprehensive Review" },
      { term: "first", week: 2, name: "Algebra: Equations and Expressions Review" },
      { term: "first", week: 3, name: "Geometry: Plane and Solid Shapes Review" },
      { term: "first", week: 4, name: "Mensuration: Area and Volume Review" },
      { term: "first", week: 5, name: "Trigonometry: Ratios and Identities Review" },
      { term: "first", week: 6, name: "Statistics and Probability Review" },
      { term: "first", week: 7, name: "Calculus: Differentiation and Integration Review" },
      { term: "first", week: 8, name: "WAEC Past Questions: Paper 1 (2015–2019)" },
      { term: "first", week: 9, name: "WAEC Past Questions: Paper 2 (2015–2019)" },
      { term: "first", week: 10, name: "NECO Past Questions Review" },
      { term: "first", week: 11, name: "Mock Examination" },
      { term: "first", week: 12, name: "Mock Examination Review" },

      { term: "second", week: 1, name: "WAEC Past Questions: Paper 1 (2020–2023)" },
      { term: "second", week: 2, name: "WAEC Past Questions: Paper 2 (2020–2023)" },
      { term: "second", week: 3, name: "Problem Areas: Vectors and Matrices" },
      { term: "second", week: 4, name: "Problem Areas: Coordinate Geometry" },
      { term: "second", week: 5, name: "Problem Areas: Probability" },
      { term: "second", week: 6, name: "Timed Practice: Full Paper Under Exam Conditions" },
      { term: "second", week: 7, name: "Final WAEC/NECO Preparation" },
    ],
  },

  {
    title: "SS 3 – English Language",
    level: "ss", className: "SS 3", subjectName: "English Language",
    description: "SS 3 English: final WAEC/NECO preparation with past papers and intensive practice.",
    topics: [
      { term: "first", week: 1, name: "Summary Writing: WAEC Style (Timed)" },
      { term: "first", week: 2, name: "Comprehension: WAEC Past Passages (2015–2019)" },
      { term: "first", week: 3, name: "Essay Writing: All Types Review" },
      { term: "first", week: 4, name: "Oral English: WAEC Phonetics" },
      { term: "first", week: 5, name: "Literature: Prose – Themes and Characters" },
      { term: "first", week: 6, name: "Literature: Drama – Plot and Conflict" },
      { term: "first", week: 7, name: "Literature: Poetry – Devices and Appreciation" },
      { term: "first", week: 8, name: "Grammar: Common WAEC Question Types" },
      { term: "first", week: 9, name: "WAEC Past Questions: Comprehension (2019–2022)" },
      { term: "first", week: 10, name: "WAEC Past Questions: Literature (2019–2022)" },
      { term: "first", week: 11, name: "Mock Examination" },
      { term: "first", week: 12, name: "Mock Examination Review" },

      { term: "second", week: 1, name: "Final Comprehension Practice" },
      { term: "second", week: 2, name: "Final Essay Writing Practice" },
      { term: "second", week: 3, name: "Final Literature Practice" },
      { term: "second", week: 4, name: "Oral English Final Drill" },
      { term: "second", week: 5, name: "Full Mock Paper Under Exam Conditions" },
      { term: "second", week: 6, name: "WAEC/NECO Final Preparation" },
    ],
  },

  {
    title: "SS 3 – Physics",
    level: "ss", className: "SS 3", subjectName: "Physics",
    description: "SS 3 Physics: comprehensive WAEC/NECO revision with practical and theory past questions.",
    topics: [
      { term: "first", week: 1, name: "Mechanics: Complete Review" },
      { term: "first", week: 2, name: "Thermal Physics: Complete Review" },
      { term: "first", week: 3, name: "Waves and Optics: Complete Review" },
      { term: "first", week: 4, name: "Electricity and Magnetism: Complete Review" },
      { term: "first", week: 5, name: "Modern Physics: Complete Review" },
      { term: "first", week: 6, name: "WAEC Past Questions: Objectives (2015–2019)" },
      { term: "first", week: 7, name: "WAEC Past Questions: Theory (2015–2019)" },
      { term: "first", week: 8, name: "WAEC Practical: Skill Building" },
      { term: "first", week: 9, name: "WAEC Past Questions: Objectives (2020–2023)" },
      { term: "first", week: 10, name: "WAEC Past Questions: Theory (2020–2023)" },
      { term: "first", week: 11, name: "Mock Examination" },
      { term: "first", week: 12, name: "Mock Examination Review" },

      { term: "second", week: 1, name: "Problem-Solving: Calculations and Numerical Questions" },
      { term: "second", week: 2, name: "Practical Revision: Measuring Instruments" },
      { term: "second", week: 3, name: "Full Mock Paper: Objectives + Theory" },
      { term: "second", week: 4, name: "WAEC/NECO Final Preparation" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════
  // Primary (Selected Subjects)
  // ═══════════════════════════════════════════════════════════════════
  {
    title: "Primary 4 – Mathematics",
    level: "primary", className: "Primary 4", subjectName: "Mathematics",
    description: "Primary 4 Mathematics covering whole numbers, fractions, basic geometry, and measurement.",
    topics: [
      { term: "first", week: 1, name: "Whole Numbers: Reading and Writing up to 1,000,000" },
      { term: "first", week: 2, name: "Addition and Subtraction of Large Numbers" },
      { term: "first", week: 3, name: "Multiplication: 2-digit by 2-digit" },
      { term: "first", week: 4, name: "Division with Remainders" },
      { term: "first", week: 5, name: "Factors and Multiples" },
      { term: "first", week: 6, name: "Fractions: Proper, Improper and Mixed" },
      { term: "first", week: 7, name: "Addition and Subtraction of Fractions" },
      { term: "first", week: 8, name: "Decimals: Reading and Writing" },
      { term: "first", week: 9, name: "Money: Buying and Selling" },
      { term: "first", week: 10, name: "Time: 12-Hour and 24-Hour Clock" },
      { term: "first", week: 11, name: "Length and Distance: Metric Units" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Weight and Mass: Kilograms and Grams" },
      { term: "second", week: 2, name: "Capacity: Litres and Millilitres" },
      { term: "second", week: 3, name: "Perimeter of Plane Shapes" },
      { term: "second", week: 4, name: "Area: Rectangles and Squares" },
      { term: "second", week: 5, name: "Angles: Types and Measurement" },
      { term: "second", week: 6, name: "Lines: Types and Properties" },
      { term: "second", week: 7, name: "Triangles: Properties and Types" },
      { term: "second", week: 8, name: "Quadrilaterals: Properties" },
      { term: "second", week: 9, name: "Data Handling: Tally Charts and Bar Graphs" },
      { term: "second", week: 10, name: "Data Handling: Pictograms" },
      { term: "second", week: 11, name: "Problem Solving: Word Problems" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Number Patterns and Sequences" },
      { term: "third", week: 2, name: "Simple Fractions of Quantities" },
      { term: "third", week: 3, name: "Percentage: Introduction" },
      { term: "third", week: 4, name: "Symmetry and Reflections" },
      { term: "third", week: 5, name: "3D Shapes: Faces, Edges and Vertices" },
      { term: "third", week: 6, name: "Mixed Revision and Examination" },
    ],
  },

  {
    title: "Primary 5 – Basic Science",
    level: "primary", className: "Primary 5", subjectName: "Basic Science",
    description: "Primary 5 Basic Science covering living things, materials, forces, and health.",
    topics: [
      { term: "first", week: 1, name: "Living and Non-Living Things" },
      { term: "first", week: 2, name: "Plant Parts and Their Functions" },
      { term: "first", week: 3, name: "Animals: Classification" },
      { term: "first", week: 4, name: "The Environment: Natural and Artificial" },
      { term: "first", week: 5, name: "Soil: Types and Properties" },
      { term: "first", week: 6, name: "Water: Sources and Uses" },
      { term: "first", week: 7, name: "Air: Properties and Uses" },
      { term: "first", week: 8, name: "Materials: Properties" },
      { term: "first", week: 9, name: "Simple Machines in Everyday Life" },
      { term: "first", week: 10, name: "Forces: Pushing, Pulling and Gravity" },
      { term: "first", week: 11, name: "Light and Shadow" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Sound: How We Hear" },
      { term: "second", week: 2, name: "Heat and Temperature" },
      { term: "second", week: 3, name: "Electricity: Conductors and Insulators" },
      { term: "second", week: 4, name: "The Human Body: Major Organs" },
      { term: "second", week: 5, name: "Nutrition: Balanced Diet" },
      { term: "second", week: 6, name: "Diseases: Common Childhood Diseases" },
      { term: "second", week: 7, name: "Personal Hygiene and Sanitation" },
      { term: "second", week: 8, name: "First Aid: Basic Procedures" },
      { term: "second", week: 9, name: "Drug Abuse: Dangers" },
      { term: "second", week: 10, name: "Technology: Tools and Inventions" },
      { term: "second", week: 11, name: "ICT: Computers in Everyday Life" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "Weather and Climate" },
      { term: "third", week: 2, name: "Pollution: Types and Effects" },
      { term: "third", week: 3, name: "Conservation of Natural Resources" },
      { term: "third", week: 4, name: "Recycling and Waste Management" },
      { term: "third", week: 5, name: "Space: The Solar System" },
      { term: "third", week: 6, name: "Revision and Examination" },
    ],
  },

  {
    title: "Primary 6 – English Studies",
    level: "primary", className: "Primary 6", subjectName: "English Studies",
    description: "Primary 6 English Studies: reading, writing, grammar, and oral skills for FSLC preparation.",
    topics: [
      { term: "first", week: 1, name: "Reading: Comprehension Passages" },
      { term: "first", week: 2, name: "Nouns: Common, Proper, Collective and Abstract" },
      { term: "first", week: 3, name: "Pronouns and Their Usage" },
      { term: "first", week: 4, name: "Verbs: Action, Helping and Linking Verbs" },
      { term: "first", week: 5, name: "Adjectives: Degrees of Comparison" },
      { term: "first", week: 6, name: "Adverbs and Their Types" },
      { term: "first", week: 7, name: "Composition: Story Writing" },
      { term: "first", week: 8, name: "Composition: Descriptive Writing" },
      { term: "first", week: 9, name: "Punctuation: Full Stop, Comma, Apostrophe" },
      { term: "first", week: 10, name: "Letter Writing: Informal Letter" },
      { term: "first", week: 11, name: "Oral English: Vowel and Consonant Sounds" },
      { term: "first", week: 12, name: "Revision and Examination" },

      { term: "second", week: 1, name: "Tenses: Present, Past and Future" },
      { term: "second", week: 2, name: "Direct and Indirect Speech" },
      { term: "second", week: 3, name: "Comprehension: Answering Questions" },
      { term: "second", week: 4, name: "Vocabulary: Synonyms and Antonyms" },
      { term: "second", week: 5, name: "Conjunctions and Prepositions" },
      { term: "second", week: 6, name: "Composition: Argumentative Writing" },
      { term: "second", week: 7, name: "Poem: Reading and Appreciation" },
      { term: "second", week: 8, name: "Summary: How to Summarise a Passage" },
      { term: "second", week: 9, name: "Reading Aloud and Pronunciation" },
      { term: "second", week: 10, name: "Essay: My School / My Community" },
      { term: "second", week: 11, name: "FSLC Past Questions Review" },
      { term: "second", week: 12, name: "Revision and Examination" },

      { term: "third", week: 1, name: "FSLC Preparation: Grammar Drills" },
      { term: "third", week: 2, name: "FSLC Preparation: Comprehension" },
      { term: "third", week: 3, name: "FSLC Preparation: Composition" },
      { term: "third", week: 4, name: "FSLC Mock Examination" },
      { term: "third", week: 5, name: "Final Revision and Examination" },
    ],
  },
];

export async function seedCurriculumTemplates(): Promise<void> {
  console.log("🎓 Seeding curriculum templates...");

  const existing = await db.select().from(curriculumTemplates);
  if (existing.length > 0) {
    console.log(`ℹ️  Curriculum templates already seeded (${existing.length} templates found) — skipping.`);
    return;
  }

  let templatesCreated = 0;
  let topicsCreated = 0;

  for (const tpl of TEMPLATES) {
    const [inserted] = await db.insert(curriculumTemplates).values({
      title: tpl.title,
      level: tpl.level,
      className: tpl.className,
      subjectName: tpl.subjectName,
      description: tpl.description,
      isPublished: true, // available to admins immediately
    }).returning();

    if (tpl.topics.length > 0) {
      const topicRows = tpl.topics.map((t, i) => ({
        templateId: inserted.id,
        term: t.term,
        weekNumber: t.week,
        orderNumber: i,
        name: t.name,
        description: t.description ?? null,
      }));
      await db.insert(curriculumTemplateTopics).values(topicRows);
      topicsCreated += topicRows.length;
    }
    templatesCreated++;
  }

  console.log(`✅ Curriculum templates seeded: ${templatesCreated} templates, ${topicsCreated} topics.`);
}
